### ISSUE TITLE
Data / Implement geospatial view

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3800]
We should provide a simple map view of a dataset if it contains geospatial columns. Perspective doesn't provide a native map view, so we may implement something based on Leaflet.

The idea is that if a table contains some column/s with an specific format, we generate the map visualization. 

- define the format of the columns we accept (lat+lon, geojson, points, polygons...?). Start with something simple
- if the front detect this column/s, it shows the map. Decide where we show it. As a new tab? A block in the dataset home?

**Comment by furilo** [comment]
@jorgeatgu would it be possible to implement a new visualization type via a Plugin for Perspective? (Does Perspective plugins even exist?)

**Comment by jorgeatgu** [comment]
The best thing to implement a new visualization is to build a Perspective plugin.

We’ve defined a roadmap:

1. Create a plugin
 - We have the skeleton of the plugin, and in the first test, we are showing the census of Getafe 
that come in GeoJson format.
 -Detect if the dataset contains geospatial information.
- If the dataset contains geospatial information, remove the LIMIT to shown all polygons.

2. Get data from API to map
 - We have to deal with different formats (geojson, points, polygons, etc.).
 - Transform the geometry layer for Leaflet to draw the map.
 - Includes the properties to show on the map for every Layer.
 - Workflow: save a new visualization as map, load, and edit in visualizations tabs
 
3. Map interactivity
 - Update the value shown on the map.
 - Show a tooltip with the value(s).
 - Color scales for the map
 
4. Test
Define a test set with different cases, create a CSV with invalid GeoJson, another with a null value, an empty object. 

![map-plugin](https://user-images.githubusercontent.com/2649175/114555882-6c279f80-9c68-11eb-94bf-dfda6daab168.gif)

@Crashillo

**Comment by ferblape** [comment]
Some questions:

- from which column are you reading the geometry? that column will contain the geometry in plain text format (basically it will contain a topojson with a point, polygon, multipolygon...)
- if a dataset contains 10 columns with data attributes, how are you going to select which one do you want to use? Is that possible in the plugin?
- how are you planning to center the map?
- do you need examples of datasets?

**Comment by jorgeatgu** [comment]
> from which column are you reading the geometry? that column will contain the geometry in plain text format (basically it will contain a topojson with a point, polygon, multipolygon...)

We're reading the geometry of the geometry column, and the type of the column is a string.

> if a dataset contains 10 columns with data attributes, how are you going to select which one do you want to use? Is that possible in the plugin?

We search for the first numeric field in the data. Then the user can change that selection in the perspective UI 

> how are you planning to center the map?

The map is automatically centered with Leaflet's `fitBounds function` based on the polygons returned by the query.

> do you need examples of datasets?

Yes!!

**Comment by Crashillo** [comment]
> the geometry column

A column called _geometry_

**Comment by ferblape** [comment]
@Crashillo @jorgeatgu see https://github.com/PopulateTools/gobierto/issues

It's important that the visualization doesn't break when:

- the custom field doesn't exist
- the custom field has an invalid column name

That custom field will be avaiable in the /meta endpoint so you'll be able to read it from there. In the meantime you can create it manually in your admin UI

**Comment by Crashillo** [comment]
> the custom field doesn't exist

This is the default behaviour. It uses the first column of the dataset.

> the custom field has an invalid column name

Because the column is not found, nothing is displayed in the map, but the tileLayer itself, which initializes by default, that is, a worldwide view

**Comment by ferblape** [comment]
@jorgeatgu @Crashillo we have added the custom field `gobierto-default-geometry-data-column` to read from that column the numeric value by default as we aggreed but it's not working in staging. Could you review?

**Comment by Crashillo** [comment]
Replace this line: https://github.com/PopulateTools/gobierto/blob/b7088a030d620c362a6a753e0ded85dca3fdcb04/app/javascript/gobierto_data/webapp/components/Dataset.vue#L361
with: `gobiertoDefaultGeometryDataColumn: metric,`

**Comment by ferblape** [comment]
could you change this please @jorgeatgu ?

**Comment by jorgeatgu** [comment]
> could you change this please @jorgeatgu ?

Done!

**Comment by ferblape** [comment]
Did you deploy? It's not working to me https://getafe.gobify.net/datos/secciones-censales?sql=SELECT%2520%2a%2520FROM%2520secciones_censales I still see it's using objectId instead of csec which is the column I configured

**Comment by jorgeatgu** [comment]
> Did you deploy? It's not working to me https://getafe.gobify.net/datos/secciones-censales?sql=SELECT%2520%2a%2520FROM%2520secciones_censales I still see it's using objectId instead of csec which is the column I configured

Fixed. The "pre-publish" script of the perspective-map wasn't working and didn't compile the code.
![Screenshot 2021-05-11 at 11 48 42](https://user-images.githubusercontent.com/2649175/117795878-d8d59000-b24e-11eb-80d7-aeb24b4334e2.png)
